### ISSUE TITLE
Project needs a logo

### ISSUE THREAD

**Issue by chris-laplante** [yoctoproject/bb-datastore-playground#1]
It would be greatly appreciated if someone who does graphic design could whip up a quick logo. ChatGPT produced this which I kind of like, but don't have the skills to draw as a vector graphic:

![image](https://github.com/yoctoproject/bb-datastore-playground/assets/40474653/801fc3e7-9d68-4656-ada8-dcb35a04d787)

**Comment by jenisesc** [comment]
Hello, I would like to work on this :)

**Comment by mostthingsweb** [comment]
> Hello, I would like to work on this :)

Yes please! Have at it :). And if you've got a different idea for a logo in mind feel free.

**Comment by jenisesc** [comment]
Please assign me this project. And would you mind giving some context about the logo and the concept? So maybe I can come up with something

**Comment by chris-laplante** [comment]
I will write a better description later when I have more time, but you can think of this project as sort of like Godbolt (https://godbolt.org/) but for BitBake: https://docs.yoctoproject.org/bitbake/. So an online editor sort of thing, which some ability to run code.

**Comment by jenisesc** [comment]
Hello, A quick follow up, what is the name of your project?

**Comment by chris-laplante** [comment]
> Hello, A quick follow up, what is the name of your project?

BB Datastore Playground

**Comment by jenisesc** [comment]
Hi, I just made a pull request, let me know if it's all good, or you need anything else?

**Comment by mostthingsweb** [comment]
> Hi, I just made a pull request, let me know if it's all good, or you need anything else?

I love it, thanks so much :)!

**Comment by mostthingsweb** [comment]
Out of curiosity, how did you find this issue btw?

**Comment by jenisesc** [comment]
thank you!! glad to help :). I found this issue on https://goodfirstissue.dev

**Comment by chris-laplante** [comment]
> thank you!! glad to help :). I found this issue on https://goodfirstissue.dev

Ah cool, didn't know that site existed :). Thanks again! I really appreciate it :)
